apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: picoyplaca
resources:
- ../../base
images:
- name: mauro101/picoyplaca-backend
  newName: mauro101/picoyplaca-backend
  newTag: 2f705ff0a2c15b06ab2a058888a75749f356d329
- name: mauro101/picoyplaca-frontend
  newName: mauro101/picoyplaca-frontend
  newTag: 2f705ff0a2c15b06ab2a058888a75749f356d329
