apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: picoyplaca
resources:
- ../../base
images:
- name: mauro101/picoyplaca-backend
  newName: mauro101/picoyplaca-backend
  newTag: 49d2829ebfd86e78672be666c4787d60108eb0aa
- name: mauro101/picoyplaca-frontend
  newName: mauro101/picoyplaca-frontend
  newTag: 49d2829ebfd86e78672be666c4787d60108eb0aa
